Week 5 homework
JovanTomasevic/TA_Reskill pull request #1
Opened 2022-10-28 10:41 UTC by JovanTomasevic

2022-11-04 15:02 UTC, PetkovicStefan requested changes
Okej je zadatak, samo jos neke sitnice da ispravis. I vidim da ti se jos pushaju stvari u env-api.properties file, proveri da li ti se nalazi taj file u .gitIgnore jer tu ima osetljivih podataka

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/asserts/ActivitesAssert.java
> +        softAssert.assertEquals(actualResponse.getDueDate(), expectedResponse.getDueDate().substring(0,actualResponse.getDueDate().length()), "DueDate didn't match");
Sto si ovde morao substring? jer opet vidim da si uzeo ceo expectedResponse.getDueDate

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/asserts/ActivitesAssert.java
> +    public void assertActivityDeleted(GetAllActivitiesResponse[] getAllActivitiesResponse) {
Moze i ovako, ali bolje da si napravio metodu koja trazi activity u listi i vraca true/false i onda samo pozoves tu metodu ovde, a mozes je iskoristiti i u drugim testovima

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/asserts/AuthorAssert.java
> +        for(int i = 0; i < getAllAuthors.length; i++){
Isto i ovde :)

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/suites/ActivitiesTests.java
> +        activityId = actualResponse.getId();
Sta ce ti ovo ovde? :D

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/suites/ActivitiesTests.java
> +        CommonActivitiesResponse actualResponse = ActivitiesAPI.updatedActivity(activityRequest, activityId);
activityId pripremas prethodnim testom, to nikako nije dobro, rekli smo da testovi moraju da budu nezavisni jedni od drugih, znaci ovde prvo radis pripremu podatka to mozes cak i u provideru da radis da napravis jednog usera i da njegov id prosledis kroz provider kao i request i onda da koristis ovde

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/suites/ActivitiesTests.java
> +        ActivitiesAPI.deleteActivity(activityId);
Isto i za delete, activityId pripremi u okviru ovog testa

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/suites/ActivitiesTests.java
> +        activitesAssert.assertActivityDeleted(getAllActivitiesResponse);
I ako lepo napravis metodu koja proverava usera, ovde neces imati potrebe da pozivas activitiesAssert vec bi samo stavio Assert.false(isActivitiesExistInList(ActivitiesAPI.getAllActivitiesResponse()));

2022-11-04 15:02 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/suites/AuthorTests.java
> +public class AuthorTests extends TestBase {
Kod svih test klasa imas iste greske pa da ti ne komentarisem svuda isto, prodji kroz sve i ispravi ono sto je komentarisano u Activities testovima

2022-11-04 15:14 UTC, JovanTomasevic commented on api-tests/src/test/java/com/projectname/api/tests/functional/asserts/ActivitesAssert.java
> +        softAssert.assertEquals(actualResponse.getDueDate(), expectedResponse.getDueDate().substring(0,actualResponse.getDueDate().length()), "DueDate didn't match");
Format datuma je cudan. Dodaje sam dvije 0 na kraju, a kad uzmem ovako kao substring kad uzmem ali citav onda ih ne dodaje. Ovako kao na screnshotu:
<img width="253" alt="dueDate" src="https://user-images.githubusercontent.com/114058497/200009988-c17404ea-d853-4c29-b08e-af9700f9a955.png">

2022-11-04 15:32 UTC, PetkovicStefan commented on api-tests/src/test/java/com/projectname/api/tests/functional/asserts/ActivitesAssert.java
> +        softAssert.assertEquals(actualResponse.getDueDate(), expectedResponse.getDueDate().substring(0,actualResponse.getDueDate().length()), "DueDate didn't match");
Razumem. onda nek ostane tako

2022-11-17 12:55 UTC, PetkovicStefan approved these changes

2022-11-17 13:04 UTC, merged